# This file was modified from https://github.com/ammaraskar/sphinx-action-test/blob/master/.github/workflows/pull_request.yml

name: Pull Request Docs Check

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip' # caching pip dependencies
    # Standard drop-in approach that should work for most people.
    #- uses: ammaraskar/sphinx-action@7.3.7
    #  with:
    #    docs-folder: "docs/"
    # Example of using a custom build-command.
    #- uses: ammaraskar/sphinx-action@master
    #  with:
    #    build-command: "sphinx-build -b html . _build"
    #    docs-folder: "docs2/"
    ## Grabbing custom dependencies and building as a pdf.
    #- uses: ammaraskar/sphinx-action@master
    #  with:
    #    pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
    #    build-command: "make latexpdf"
    #    docs-folder: "docs2/"
    # Great extra actions to compose with:
    # Create an artifact of the html output.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
    - name: Build documentation
      run: cd docs && make html
    - uses: actions/upload-artifact@v4
      with:
        name: DocumentationHTML
        path: docs/build/html/